# Generated by Django 5.0.7 on 2024-07-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "indicator",
                    models.FloatField(blank=True, null=True, verbose_name="Показатель"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "ЕДиница измерения",
                "verbose_name_plural": "Единицы измерений",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Deviations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "critical",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="critical_dev",
                        to="medical.condition",
                    ),
                ),
                (
                    "marked",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="marked_dev",
                        to="medical.condition",
                    ),
                ),
                (
                    "moderate",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="moderate_dev",
                        to="medical.condition",
                    ),
                ),
                (
                    "normal",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="normal_dev",
                        to="medical.condition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "deviations",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medical.deviations",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medical.measurement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Марке",
                "verbose_name_plural": "Маркеры",
                "ordering": ["-name"],
            },
        ),
    ]
