# Generated by Django 5.0.7 on 2024-07-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condition",
            options={"verbose_name": "Условие", "verbose_name_plural": "Условия"},
        ),
        migrations.AddField(
            model_name="condition",
            name="condition_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Больше"),
                    ("2", "Меньше"),
                    ("3", "Больше или равно"),
                    ("4", "Меньше или равно"),
                    ("5", "Равно"),
                ],
                max_length=1,
                null=True,
                verbose_name="Тип условия",
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="indicators_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Норма"),
                    ("2", "Умеренные отклонения"),
                    ("3", "Выраженные отклонения"),
                    ("4", "Критические отклонения"),
                ],
                max_length=1,
                null=True,
                verbose_name="Тип индикаторов",
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="is_age",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Условие возраста"
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("1", "Мужской"), ("2", "Женский"), ("3", "Общий")],
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
