# Generated by Django 5.0.7 on 2024-07-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0003_alter_deviations_options_alter_marker_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="markercondition",
            options={
                "ordering": ["-name"],
                "verbose_name": "Маркер с условием",
                "verbose_name_plural": "Маркеры с условием",
            },
        ),
        migrations.AlterField(
            model_name="condition",
            name="condition_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (">", "Больше"),
                    ("<", "Меньше"),
                    (">=", "Больше или равно"),
                    ("<=", "Меньше или равно"),
                    ("==", "Равно"),
                ],
                max_length=2,
                null=True,
                verbose_name="Тип условия",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="indicators_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Норма", "Норма"),
                    ("Умеренные отклонения", "Умеренные"),
                    ("Выраженные отклонения", "Выраженные"),
                    ("Критические отклонения", "Критические"),
                ],
                max_length=32,
                null=True,
                verbose_name="Тип индикаторов",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("Муж", "Мужской"), ("Жен", "Женский"), ("Общ", "Общий")],
                max_length=3,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
