# Generated by Django 5.0.7 on 2024-07-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical", "0004_alter_markercondition_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviations",
            name="critical",
            field=models.ManyToManyField(
                related_name="critical_dev", to="medical.condition"
            ),
        ),
        migrations.AlterField(
            model_name="deviations",
            name="marked",
            field=models.ManyToManyField(
                related_name="marked_dev", to="medical.condition"
            ),
        ),
        migrations.AlterField(
            model_name="deviations",
            name="moderate",
            field=models.ManyToManyField(
                related_name="moderate_dev", to="medical.condition"
            ),
        ),
        migrations.AlterField(
            model_name="deviations",
            name="normal",
            field=models.ManyToManyField(
                related_name="normal_dev", to="medical.condition"
            ),
        ),
        migrations.CreateModel(
            name="UserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название состояния"),
                ),
                (
                    "marksers",
                    models.ManyToManyField(related_name="states", to="medical.marker"),
                ),
            ],
            options={
                "verbose_name": "Состояние",
                "verbose_name_plural": "Состояния",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="PatientSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "states",
                    models.ManyToManyField(
                        related_name="systems", to="medical.userstate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Система",
                "verbose_name_plural": "Системы",
                "ordering": ["-name"],
            },
        ),
    ]
